### ISSUE TITLE
CMAKE file error.

### ISSUE THREAD

**Issue by Taher0321** [shivang51/portaudio#2]
![WhatsApp Image 2024-01-01 at 8 08 01 PM](https://github.com/shivang51/portaudio/assets/151981876/5e4d997b-0d65-4ccd-a2fa-086ca4b5f1f8)
We have created a CMAKE file in which we are facing path errors, we tried forward,backward slash solution but still facing the same error. Kindly direct

**Comment by shivang51** [comment]
This issue  is not related to this repositry please read the CMAKE docs to figure this out.
[This](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) would be a good starting point.
